version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Logging into ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Getting the Git commit SHA
      - export GIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - echo Git SHA  $GIT_SHA
      
  build:
    commands:
      - echo Start building ...
      - echo Building docker image for backend ..
      - docker build -t backend:$GIT_SHA starter/backend/.
      - docker tag backend:$GIT_SHA $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:$GIT_SHA
      - echo Building docker image for frontend ..
      - docker build --build-arg REACT_APP_MOVIE_API_URL=http://backend:5000 -t frontend:$GIT_SHA starter/frontend/.
      - docker tag frontend:$GIT_SHA $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/frontend:$GIT_SHA
  post_build:
    commands:
      - echo Completed build ...
      - echo Pushing the docker image to ECR repo
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:$GIT_SHA
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/frontend:$GIT_SHA
      - echo Build Complete
