apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
images:
  - name: backend
    newName: <your-ecr-repository-uri>
    newTag: <your-tag>
namespace: default
