name: backend-cd
on:
  pull_request:
    branches: [main]
    paths:
      - 'setup/frontend/**'
jobs:  
  backend-cd:
    name: backend-cd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4