name: frontend-ci
on:
  pull_request:
    branches: [main]
    paths:
      - 'setup/frontend/**'
jobs:  
  frontend-ci:
    name: backend-cd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4